//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.07 at 03:31:02 PM EEST 
//


package xml_bind_xjc;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml_bind_xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Varsta_QNAME = new QName("", "varsta");
    private final static QName _Oras_QNAME = new QName("", "oras");
    private final static QName _Nume_QNAME = new QName("", "nume");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml_bind_xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Persoana }
     * 
     */
    public Persoana createPersoana() {
        return new Persoana();
    }

    /**
     * Create an instance of {@link Persoane }
     * 
     */
    public Persoane createPersoane() {
        return new Persoane();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "varsta")
    public JAXBElement<BigInteger> createVarsta(BigInteger value) {
        return new JAXBElement<BigInteger>(_Varsta_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oras")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOras(String value) {
        return new JAXBElement<String>(_Oras_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nume")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNume(String value) {
        return new JAXBElement<String>(_Nume_QNAME, String.class, null, value);
    }

}
